# Generated by Django 3.1.2 on 2020-12-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasell_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['count', 'price'], 'verbose_name': 'جزییات محصول', 'verbose_name_plural': 'اطلاعات جزییات محصولات'},
        ),
    ]
