# Generated by Django 3.1.2 on 2020-10-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasell_products_category', '0001_initial'),
        ('gasell_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='gasell_products_category.ProductCategory', verbose_name='دسته بندی ها'),
        ),
    ]
