# Generated by Django 3.1.2 on 2020-12-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasell_products', '0003_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'price', 'active', 'exist'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='exist',
            field=models.BooleanField(default=False, verbose_name='موجود / ناموجود'),
        ),
    ]
