# Generated by Django 3.1.2 on 2020-12-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasell_products', '0004_auto_20201202_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
