# Generated by Django 3.1.2 on 2020-12-13 19:10

from django.db import migrations, models
import gasell_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('gasell_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='pfp',
            field=models.ImageField(default='./assets/default_pfp.jpeg', upload_to=gasell_account.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
