# Generated by Django 3.1.2 on 2020-12-13 19:22

from django.db import migrations, models
import gasell_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('gasell_account', '0002_profileuser_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='pfp',
            field=models.ImageField(default='./images/default_pfp.jpeg', upload_to=gasell_account.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
