# Generated by Django 3.1.2 on 2020-12-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasell_account', '0004_auto_20201214_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
