# Generated by Django 3.1.2 on 2020-12-14 10:34

from django.db import migrations, models
import gasell_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('gasell_account', '0005_remove_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='./accounts/default_pfp.jpeg', upload_to=gasell_account.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
