# Generated by Django 3.1.2 on 2020-12-06 18:01

from django.db import migrations, models
import gasell_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('gasell_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=gasell_settings.models.upload_image_path, verbose_name='تصویر لوگو'),
        ),
    ]
